name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      TMPDIR: /tmp
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: ./stest.sh
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: echo "Updating brew formula"
